# Домашняя работа

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Задание 1
Изобразите с помощью matplotlib. Изобразите точку x + 2y + 3z. Найдите угол между векторами x, y и x, z.

In [ ]:
x = np.array([1,1])
y = np.array([2, 0])
z = np.array([0,2])

In [ ]:
plt.plot(x)
plt.plot(y)
plt.plot(z)

In [ ]:
plt.plot(x + 2 * y + 3 * z)

In [ ]:
import scipy.spatial.distance
vectors_xy = np.array([x, y])
vectors_xz = np.array([x, z])
dist_xy = scipy.spatial.distance.pdist(vectors_xy, 'cosine')
dist_xz = scipy.spatial.distance.pdist(vectors_xz, 'cosine')
angle_xy = np.rad2deg(np.arccos(1 - dist_xy))
angle_xz = np.rad2deg(np.arccos(1 - dist_xz))
print(f"Угол между x и y: {round(angle_xy[0])} градусов")
print(f"Угол между x и z: {round(angle_xz[0])} градусов")


### Задание 2
Найдите собственные значения и собственные вектора матриц (необходимо решение на numpy и решение по алгоритму на бумажке). Для матрицы 3x3 можно посмотреть на корни характеристического многочлена, посчитанные в numpy.

In [12]:
m1 = np.array([[2, 2],
               [1, 3]])

m2 = np.array([[4, 1, -1],
               [1, 4, -1],
               [-1, -1, 4]])

In [13]:
np.linalg.eig(m1)

(array([1., 4.]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

In [14]:
np.linalg.eig(m2)

(array([3., 6., 3.]),
 array([[-0.81649658,  0.57735027, -0.27658128],
        [ 0.40824829,  0.57735027,  0.8035929 ],
        [-0.40824829, -0.57735027,  0.52701162]]))

### Задание 3
Найдите сингулярное разложение матрицы.

In [7]:
m3 = np.array([[1, 2],
               [2, 3]])

In [10]:
U, s, V = np.linalg.svd(m3)
S = np.zeros((m3.shape[0], m3.shape[1]))
S[:m3.shape[0], :m3.shape[0]] = np.diag(s)
n_component = 1
S = S[:, :n_component]
V = V[:n_component, :]
A = U.dot(S.dot(V))
print(A)

[[1.17082039 1.89442719]
 [1.89442719 3.06524758]]


Ответ преподователя от 27.05.2020

Добрый день!

Спасибо за задание!

Всё сделанное верно!

Необходимо добавить решение Задания 2 на листочке по алгоритму из лекции.

# Решение на листочке (задание 2)

In [11]:
m_original = np.array([[2, 2],
                       [1, 3]])

### шаг 1: умножаем матрицу на [лямда E] (диагональная матрица с лямда)

[2-lamda,     2         ]

[1,              3-lamda]

### шаг 2: получаем детерминант полученной матрицы
((2 - lamda) * (3-lamda)) - (2 * 1) = 0

6 - 3 * lamda - 2 * lamda + lamda ** 2 - 2 = 0

lamda ** 2 - 5 * lamda + 4 = 0

### шаг 3: находим корни уравнения

а)

D = (-5) ** 2 - 4 * 1 * 4 = 25 - 16 = 9


б)

lamda1 = (5 - 3) / 2 * 1

lamda2 = (5 + 3) / 2 * 1

в)
#### Собственные значения матрицы
lamda1 = 1

lamda2 = 4

### шаг 4.1 для lamda1: 

а)
    
{ (2 - 1) * x + 2 * y = 0

{ 1 * x + (3 - 1) * y = 0

а2)
#### Вектор для lamda1
x = -2 * y

### шаг 4.2 для lamda2: 

а)
    
{ (2 - 4) * x + 2 * y = 0

{ 1 * x + (3 - 4) * y = 0

а2)
#### Вектор для lamda2
x = y